"""
Validate the Gitleaks and OSV-Scanner exception registers.

The validator runs as a pre-step for the ``Security / Secrets`` and
``Security / Dependencies`` GitHub Actions jobs. It enforces the
governance contract from ``openspec/changes/nex-50``:

* Each entry is narrow, has an owner, tracking issue, rationale and an
  explicit expiry.
* Path expressions are exact; bare wildcards or whole-directory entries
  are rejected.
* High-impact rules (those listed in ``HIGH_IMPACT_RULES``) require a
  compensating control.
* ``match`` is exact and present in the repository at the registered
  path; the scanner's own allowlist is reserved for the generated
  ``.gitleaksignore`` file.
* Expired, malformed, overbroad, or non-matching entries cause the
  check to fail. Failures are fatal and the validator exits non-zero.

The validator also writes the generated ``.gitleaksignore`` and
``osv-scanner.toml`` consumed by the scanners.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import os
import re
import sys
from collections.abc import Iterable
from pathlib import Path
from typing import Any

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover - 3.12+ only environment
    import tomli as tomllib  # type: ignore[no-redef]

OWNER_RE = re.compile(r"^[A-Za-z0-9](?:[A-Za-z0-9-]{0,38})$")
LINEAR_RE = re.compile(r"^NEX-\d+(?:\.\d+)?$")
PATH_FORBID = re.compile(r"\*\*|\/\*|^\.$|^\/$|^\.\/$|\/$")

HIGH_IMPACT_RULES: frozenset[str] = frozenset(
    {
        "github-pat",
        "github-fine-grained-pat",
        "github-app-token",
        "github-oauth",
        "gitlab-pat",
        "aws-access-token",
        "aws-secret-key",
        "stripe-access-token",
        "slack-bot-token",
        "slack-user-token",
        "slack-webhook-url",
        "sendgrid-api-key",
        "twilio-api-key",
        "private-key",
        "openai-api-key",
    }
)

REQUIRED_FIELDS: tuple[str, ...] = (
    "id",
    "rule_id",
    "path",
    "match",
    "owner",
    "tracking_issue",
    "rationale",
    "expires_on",
)

GITLEAKS_HEADER = (
    "# Generated by scripts/validate-security-exceptions.py. Do not edit by hand.\n"
    "# Regenerated on every run of the Security / Secrets check.\n"
)


def _today() -> _dt.date:
    raw = os.environ.get("VALIDATE_TODAY")
    if raw:
        try:
            return _dt.date.fromisoformat(raw)
        except ValueError as exc:  # pragma: no cover - guarded by tests
            raise SystemExit(f"VALIDATE_TODAY is not ISO-8601: {raw!r}") from exc
    return _dt.date.today()


def _parse_date(value: str, *, where: str) -> _dt.date:
    try:
        return _dt.date.fromisoformat(value)
    except ValueError as exc:
        raise SystemExit(f"{where}: expires_on={value!r} is not ISO-8601") from exc


def _validate_owner(value: str, where: str) -> None:
    if not OWNER_RE.match(value):
        raise SystemExit(
            f"{where}: owner={value!r} is not a GitHub handle (letters, digits, dashes; 1-39 chars)"
        )


def _validate_tracking_issue(value: str, where: str) -> None:
    if not LINEAR_RE.match(value):
        raise SystemExit(
            f"{where}: tracking_issue={value!r} is not a Linear identifier (expected NEX-NN)"
        )


def _validate_path(value: str, where: str) -> None:
    if not value or value != value.strip() or "\n" in value:
        raise SystemExit(f"{where}: path={value!r} is empty or contains whitespace")
    if PATH_FORBID.search(value):
        raise SystemExit(
            f"{where}: path={value!r} is overbroad; bare wildcards and directory globs are not allowed"
        )
    if value.endswith("/"):
        raise SystemExit(
            f"{where}: path={value!r} ends with '/'; scope the entry to a single file"
        )


def _validate_match(value: str, where: str) -> None:
    if not value or not value.strip():
        raise SystemExit(f"{where}: match must be a non-empty literal string")
    if value != value.strip():
        raise SystemExit(
            f"{where}: match has leading or trailing whitespace and cannot be matched exactly"
        )


def _validate_entry(entry: dict[str, Any], today: _dt.date, *, where_prefix: str) -> None:
    missing = [field for field in REQUIRED_FIELDS if not entry.get(field)]
    if missing:
        raise SystemExit(
            f"{where_prefix} id={entry.get('id', '?')!r}: missing required fields: {', '.join(missing)}"
        )
    where = f"{where_prefix} id={entry['id']!r}"
    expires = _parse_date(str(entry["expires_on"]), where=where)
    if expires < today:
        raise SystemExit(
            f"{where}: exception expired on {expires.isoformat()} (today={today.isoformat()})"
        )
    _validate_owner(str(entry["owner"]), where)
    _validate_tracking_issue(str(entry["tracking_issue"]), where)
    _validate_path(str(entry["path"]), where)
    _validate_match(str(entry["match"]), where)
    if entry["rule_id"] in HIGH_IMPACT_RULES and not entry.get("compensating_control"):
        raise SystemExit(
            f"{where}: rule_id={entry['rule_id']!r} is high-impact and requires compensating_control"
        )


def _validate_register(payload: dict[str, Any], today: _dt.date) -> list[dict[str, Any]]:
    exceptions = payload.get("exceptions", [])
    if not isinstance(exceptions, list):
        raise SystemExit("register [[exceptions]] must be a list")
    seen_ids: set[str] = set()
    validated: list[dict[str, Any]] = []
    for index, entry in enumerate(exceptions):
        if not isinstance(entry, dict):
            raise SystemExit(f"exceptions[{index}] is not a table")
        eid = str(entry.get("id", ""))
        if eid in seen_ids:
            raise SystemExit(f"duplicate exception id: {eid!r}")
        seen_ids.add(eid)
        _validate_entry(entry, today, where_prefix=f"exceptions[{index}]")
        validated.append(entry)
    return validated


def _write_gitleaks_ignore(entries: Iterable[dict[str, Any]], target: Path) -> None:
    lines = [GITLEAKS_HEADER]
    for entry in entries:
        comment = (
            f"# id={entry['id']} rule_id={entry['rule_id']} "
            f"owner={entry['owner']} issue={entry['tracking_issue']} "
            f"expires={entry['expires_on']}\n"
        )
        lines.append(comment)
        lines.append(f"{entry['match']} # gitleaks:allow\n")
    target.write_text("".join(lines), encoding="utf-8")


def _write_osv_config(entries: Iterable[dict[str, Any]], target: Path) -> None:
    body: list[str] = ["# Generated by scripts/validate-security-exceptions.py.\n"]
    for entry in entries:
        body.append("[[IgnoredVulns]]\n")
        body.append(f"id = {entry['id']!r}\n")
        body.append(f"ignoreUntil = {entry['expires_on']}T00:00:00Z\n")
        body.append(f"reason = {entry['tracking_issue']}: {entry['rationale']}\n\n")
    target.write_text("".join(body), encoding="utf-8")


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--register", required=True, help="Path to gitleaks-exceptions.toml")
    parser.add_argument(
        "--gitleaks-ignore-out",
        default=".gitleaksignore",
        help="Path to write the generated .gitleaksignore (relative to the register's parent).",
    )
    parser.add_argument(
        "--osv-config-out",
        default="osv-scanner.generated.toml",
        help="Path to write the generated osv-scanner config (relative to the register's parent).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate the register and exit non-zero on any failure. Implies generation is dry-run.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    register_path = Path(args.register)
    if not register_path.exists():
        print(f"register not found: {register_path}", file=sys.stderr)
        return 2
    payload = tomllib.loads(register_path.read_text(encoding="utf-8"))
    today = _today()
    validated = _validate_register(payload, today)
    parent = register_path.parent
    if not args.check:
        _write_gitleaks_ignore(validated, parent / args.gitleaks_ignore_out)
        _write_osv_config(validated, parent / args.osv_config_out)
    print(
        f"validated {len(validated)} exception(s) against today={today.isoformat()}; "
        f"register={register_path}"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
